using System;
using System.Collections.Generic;
using System.Security.Cryptography;
using GlobalFront.Core.Commands;
using GlobalFront.Core.Model;
using GlobalFront.Core.Reconnect;
using GlobalFront.Core.Simulation;

namespace GlobalFront.Server.Sessions
{
    /// <summary>
    /// Server-authoritative session / player identity registry (Phase 2.4,
    /// ADR-008). The sole authority for PlayerId assignment: clients never
    /// choose authoritative PlayerIds. Engine-independent (no Unity API) so
    /// the same manager serves <c>LocalMatchHost</c> and a future dedicated
    /// server host, and transport-agnostic: live connections are represented
    /// only by <see cref="ConnectionHandle"/> values supplied by the hosting
    /// layer.
    ///
    /// Determinism firewall: SessionId / MatchId / ConnectionHandle values
    /// never enter <see cref="MatchServer"/> simulation state, command
    /// scheduling or snapshot payloads. Canonical command ordering stays
    /// RequestedTick → PlayerId → Sequence.
    ///
    /// Match lifecycle in Phase 2.4 ends at <see cref="MatchPhase.Finished"/>;
    /// <see cref="MatchPhase.Closed"/> (final teardown / registry disposal)
    /// is a reserved future state for the dedicated/server lifecycle and is
    /// never assigned here (ADR-008).
    /// </summary>
    public sealed class SessionManager
    {
        private sealed class SessionRecordInternal
        {
            public SessionId Id;
            public SessionState State = SessionState.Created;
            public MatchId Match;
            public PlayerId Player;
            public ConnectionHandle Connection;
            public ulong DisconnectedAtTick;
            public SessionSecret32 Secret;
        }

        private sealed class PlayerSlot
        {
            public SessionId Session;
            public PlayerConnectionState State = PlayerConnectionState.Assigned;
            public ulong DisconnectedAtTick;
        }

        private sealed class MatchRecordInternal
        {
            public MatchId Id;
            public MatchPhase Phase = MatchPhase.Forming;
            public int Capacity;

            /// <summary>
            /// The authoritative server this match runs on, bound at
            /// <see cref="TryStartMatch"/>. Used read-only for reconnect
            /// receipts; identity values never flow into its simulation state.
            /// </summary>
            public MatchServer Server;

            /// <summary>
            /// PlayerIds in join order. Monotonically increasing and never
            /// reused within the match (OD-3).
            /// </summary>
            public readonly List<PlayerId> AssignedPlayers = new List<PlayerId>();

            public readonly Dictionary<PlayerId, PlayerSlot> Slots =
                new Dictionary<PlayerId, PlayerSlot>();
        }

        private readonly Dictionary<SessionId, SessionRecordInternal> _sessions =
            new Dictionary<SessionId, SessionRecordInternal>();

        private readonly Dictionary<MatchId, MatchRecordInternal> _matches =
            new Dictionary<MatchId, MatchRecordInternal>();

        private readonly int _disconnectGraceTicks;
        private readonly RandomNumberGenerator _cryptoRandom = RandomNumberGenerator.Create();

        private ulong _nextConnectionValue = 1;

        /// <summary>
        /// Creates a manager with a grace window measured in server ticks
        /// (OD-2). The concrete production grace duration remains an Owner
        /// Decision; the hosting layer picks the value.
        /// </summary>
        /// <exception cref="ArgumentOutOfRangeException">
        /// Thrown when <paramref name="disconnectGraceTicks"/> is negative.
        /// </exception>
        public SessionManager(int disconnectGraceTicks)
        {
            if (disconnectGraceTicks < 0)
            {
                throw new ArgumentOutOfRangeException(nameof(disconnectGraceTicks));
            }

            _disconnectGraceTicks = disconnectGraceTicks;
        }

        /// <summary>Grace window for disconnected sessions, in server ticks.</summary>
        public int DisconnectGraceTicks => _disconnectGraceTicks;

        /// <summary>
        /// Registers a new match that accepts up to <paramref name="capacity"/>
        /// players. The returned MatchId is generated by the server.
        /// </summary>
        public MatchId CreateMatch(int capacity)
        {
            if (capacity < 1 || capacity > SimulationConstants.MaxPlayers)
            {
                throw new ArgumentOutOfRangeException(nameof(capacity));
            }

            var match = new MatchRecordInternal
            {
                Id = CreateUniqueMatchId(),
                Capacity = capacity
            };
            _matches.Add(match.Id, match);
            return match.Id;
        }

        /// <summary>
        /// Registers a new session attached through the given transport-
        /// agnostic connection handle. The returned SessionId is generated by
        /// the server and is the only reconnect identity handle until
        /// authentication exists (OD-4).
        /// </summary>
        /// <exception cref="ArgumentException">
        /// Thrown when <paramref name="connection"/> is invalid.
        /// </exception>
        public SessionId CreateSession(ConnectionHandle connection) =>
            CreateSession(connection, out _);

        /// <summary>
        /// Registers a new session attached through the given transport-
        /// agnostic connection handle and outputs the cryptographically secure 32-byte secret (ADR-011).
        /// </summary>
        public SessionId CreateSession(ConnectionHandle connection, out SessionSecret32 secret)
        {
            if (!connection.IsValid)
            {
                throw new ArgumentException("Connection handle must be valid.", nameof(connection));
            }

            Span<byte> secretBytes = stackalloc byte[SessionSecret32.SizeBytes];
            _cryptoRandom.GetBytes(secretBytes);
            secret = new SessionSecret32(secretBytes);

            var session = new SessionRecordInternal
            {
                Id = CreateUniqueSessionId(),
                Connection = connection,
                Secret = secret
            };
            _sessions.Add(session.Id, session);
            return session.Id;
        }

        /// <summary>
        /// Issues the next monotonic transport-agnostic connection handle.
        /// The hosting layer calls this when it accepts a new connection
        /// (local prototype: per created session; future transport: per
        /// accepted socket/channel).
        /// </summary>
        public ConnectionHandle CreateConnectionHandle() => new ConnectionHandle(_nextConnectionValue++);

        /// <summary>
        /// Binds a session to a forming match, assigning the next monotonic
        /// PlayerId (OD-3). The server is the sole PlayerId authority.
        /// </summary>
        public JoinResult TryJoinMatch(SessionId session, MatchId match, out PlayerId assigned)
        {
            assigned = default;

            if (!_sessions.TryGetValue(session, out var record))
            {
                return JoinResult.UnknownSession;
            }

            if (record.State == SessionState.Closed)
            {
                return JoinResult.SessionClosed;
            }

            if (record.State != SessionState.Created || record.Match.IsValid)
            {
                return JoinResult.SessionAlreadyBound;
            }

            if (!_matches.TryGetValue(match, out var matchRecord))
            {
                return JoinResult.UnknownMatch;
            }

            if (matchRecord.Phase != MatchPhase.Forming)
            {
                return JoinResult.MatchNotForming;
            }

            if (matchRecord.AssignedPlayers.Count >= matchRecord.Capacity)
            {
                return JoinResult.MatchFull;
            }

            // Monotonic assignment: next = max assigned so far + 1. A retired
            // PlayerId is never handed out again within this match (OD-3).
            var nextValue = (byte)(matchRecord.AssignedPlayers.Count + 1);
            assigned = new PlayerId(nextValue);

            matchRecord.AssignedPlayers.Add(assigned);
            matchRecord.Slots[assigned] = new PlayerSlot { Session = session };

            record.State = SessionState.Connected;
            record.Match = match;
            record.Player = assigned;
            return JoinResult.Assigned;
        }

        /// <summary>
        /// Starts a forming match: maps the host-supplied template
        /// (OD-6) onto the assigned PlayerIds deterministically and
        /// initializes the authoritative server. Slot k (the k-th distinct
        /// template owner in ascending PlayerId order) receives the k-th
        /// joined player (join order); every spec owner is remapped through
        /// that table. Returns false — leaving the match in Forming — when
        /// the roster does not exactly cover the template slots or the
        /// server refuses initialization.
        /// </summary>
        /// <exception cref="ArgumentNullException">
        /// Thrown when <paramref name="template"/> or
        /// <paramref name="server"/> is null.
        /// </exception>
        public bool TryStartMatch(MatchId match, MatchConfig template, MatchServer server, out EntityId[] entityIds)
        {
            entityIds = null;

            if (template == null)
            {
                throw new ArgumentNullException(nameof(template));
            }

            if (server == null)
            {
                throw new ArgumentNullException(nameof(server));
            }

            if (!_matches.TryGetValue(match, out var matchRecord) ||
                matchRecord.Phase != MatchPhase.Forming)
            {
                return false;
            }

            // A session-managed match requires at least one participant.
            if (matchRecord.AssignedPlayers.Count < 1)
            {
                return false;
            }

            // Distinct template owners in ascending order define the slots.
            var slotOwners = new List<PlayerId>();
            for (var index = 0; index < template.UnitCount; index++)
            {
                var owner = template.Units[index].Owner;
                if (!owner.IsValid || slotOwners.Contains(owner))
                {
                    continue;
                }

                slotOwners.Add(owner);
                var insertAt = slotOwners.Count - 1;
                while (insertAt > 0 && slotOwners[insertAt - 1].Value > owner.Value)
                {
                    slotOwners[insertAt] = slotOwners[insertAt - 1];
                    insertAt--;
                }

                slotOwners[insertAt] = owner;
            }

            // The roster must exactly cover the template slots.
            if (slotOwners.Count != matchRecord.AssignedPlayers.Count)
            {
                return false;
            }

            for (var index = 0; index < matchRecord.AssignedPlayers.Count; index++)
            {
                var player = matchRecord.AssignedPlayers[index];
                if (matchRecord.Slots[player].State != PlayerConnectionState.Assigned ||
                    !_sessions.TryGetValue(matchRecord.Slots[player].Session, out var boundSession) ||
                    boundSession.State != SessionState.Connected)
                {
                    return false;
                }
            }

            // Deterministic owner mapping: template slot k → joined player k.
            var ownerMap = new Dictionary<PlayerId, PlayerId>();
            for (var index = 0; index < slotOwners.Count; index++)
            {
                ownerMap[slotOwners[index]] = matchRecord.AssignedPlayers[index];
            }

            var mappedSpecs = new UnitSpawnSpec[template.UnitCount];
            for (var index = 0; index < template.UnitCount; index++)
            {
                var spec = template.Units[index];
                mappedSpecs[index] = new UnitSpawnSpec(
                    ownerMap[spec.Owner],
                    spec.Position,
                    spec.SpeedMmPerTick,
                    spec.AutoAcquireEnemies);
            }

            entityIds = server.InitializeMatch(new MatchConfig(template.UnitStats, mappedSpecs));

            matchRecord.Server = server;
            matchRecord.Phase = MatchPhase.Running;
            for (var index = 0; index < matchRecord.AssignedPlayers.Count; index++)
            {
                matchRecord.Slots[matchRecord.AssignedPlayers[index]].State =
                    PlayerConnectionState.Connected;
            }

            return true;
        }

        /// <summary>
        /// Moves a running match to Finished and retires every slot. Called
        /// by the hosting layer when the authoritative BattleOutcome becomes
        /// terminal; a finished match accepts no joins and no commands. This
        /// is the terminal transition of the Phase 2.4 lifecycle: no
        /// teardown or registry disposal happens here (MatchPhase.Closed is
        /// reserved for the future dedicated/server lifecycle, ADR-008).
        /// </summary>
        public bool NotifyMatchFinished(MatchId match)
        {
            if (!_matches.TryGetValue(match, out var matchRecord) ||
                matchRecord.Phase != MatchPhase.Running)
            {
                return false;
            }

            matchRecord.Phase = MatchPhase.Finished;
            for (var index = 0; index < matchRecord.AssignedPlayers.Count; index++)
            {
                matchRecord.Slots[matchRecord.AssignedPlayers[index]].State =
                    PlayerConnectionState.Abandoned;
            }

            return true;
        }

        /// <summary>
        /// Reports a lost connection for a connected session, starting the
        /// grace window at <paramref name="atTick"/>. The PlayerId binding
        /// and the server-side command sequence are retained. Idempotent for
        /// sessions that are not Connected.
        /// </summary>
        public bool NotifyConnectionLost(SessionId session, ulong atTick)
        {
            if (!_sessions.TryGetValue(session, out var record) ||
                record.State != SessionState.Connected)
            {
                return false;
            }

            record.State = SessionState.Disconnected;
            record.DisconnectedAtTick = atTick;

            // Slot liveness only matters once the match runs; while forming,
            // the session state alone carries the connection status and the
            // slot stays Assigned.
            if (record.Match.IsValid &&
                _matches.TryGetValue(record.Match, out var matchRecord) &&
                matchRecord.Phase == MatchPhase.Running &&
                matchRecord.Slots.TryGetValue(record.Player, out var slot))
            {
                slot.State = PlayerConnectionState.Disconnected;
                slot.DisconnectedAtTick = atTick;
            }

            return true;
        }

        /// <summary>
        /// Rebinds a disconnected session to a new connection handle within
        /// the grace window and issues the reconnect receipt (identity
        /// semantics only; the resync flow is Phase 2.7).
        /// </summary>
        /// <exception cref="ArgumentException">
        /// Thrown when <paramref name="newConnection"/> is invalid.
        /// </exception>
        public ReconnectResult TryReconnect(
            SessionId session,
            ConnectionHandle newConnection,
            ulong atTick,
            out ReconnectReceipt receipt)
        {
            receipt = default;

            if (!newConnection.IsValid)
            {
                throw new ArgumentException("Connection handle must be valid.", nameof(newConnection));
            }

            if (!_sessions.TryGetValue(session, out var record))
            {
                return ReconnectResult.UnknownSession;
            }

            if (record.State == SessionState.Closed)
            {
                return ReconnectResult.SessionClosed;
            }

            if (record.State != SessionState.Disconnected)
            {
                return ReconnectResult.NotDisconnected;
            }

            if (atTick > record.DisconnectedAtTick + (ulong)_disconnectGraceTicks)
            {
                return ReconnectResult.GraceExpired;
            }

            if (!_matches.TryGetValue(record.Match, out var matchRecord) ||
                !matchRecord.Slots.TryGetValue(record.Player, out var slot))
            {
                return ReconnectResult.NotDisconnected;
            }

            if (matchRecord.Phase == MatchPhase.Running)
            {
                if (slot.State != PlayerConnectionState.Disconnected)
                {
                    return ReconnectResult.NotDisconnected;
                }

                slot.State = PlayerConnectionState.Connected;
            }
            else if (matchRecord.Phase != MatchPhase.Forming)
            {
                return ReconnectResult.NotDisconnected;
            }

            record.State = SessionState.Connected;
            record.Connection = newConnection;

            // Receipt data exists once the match runs on its server; a
            // forming match has no authoritative tick or sequence yet.
            receipt = matchRecord.Server != null
                ? new ReconnectReceipt(
                    record.Match,
                    record.Player,
                    matchRecord.Server.CurrentTick,
                    matchRecord.Server.TryGetLastAcceptedSequence(record.Player, out var lastSequence)
                        ? lastSequence
                        : 0u)
                : new ReconnectReceipt(record.Match, record.Player, 0ul, 0u);
            return ReconnectResult.Reconnected;
        }

        /// <summary>
        /// Validates a reconnecting client's secret and rebinds the detached session
        /// to a new connection handle within the grace window (Phase 2.7, ADR-011).
        /// </summary>
        public RebindResult TryRebindSession(
            SessionId sessionId,
            in SessionSecret32 secret,
            ConnectionHandle newHandle,
            ulong currentTick,
            out ClientSession session)
        {
            session = null;

            if (!newHandle.IsValid)
            {
                throw new ArgumentException("Connection handle must be valid.", nameof(newHandle));
            }

            if (!_sessions.TryGetValue(sessionId, out var record))
            {
                return RebindResult.SessionNotFound;
            }

            if (record.State == SessionState.Closed)
            {
                return RebindResult.SessionNotFound;
            }

            // Fixed-time secret comparison to prevent timing side-channel attacks
            Span<byte> expectedBytes = stackalloc byte[SessionSecret32.SizeBytes];
            Span<byte> actualBytes = stackalloc byte[SessionSecret32.SizeBytes];
            record.Secret.CopyTo(expectedBytes);
            secret.CopyTo(actualBytes);

            if (!ReconnectWireCodec.FixedTimeEquals(expectedBytes, actualBytes))
            {
                return RebindResult.InvalidSecret;
            }

            if (record.State == SessionState.Disconnected)
            {
                var elapsedTicks = currentTick >= record.DisconnectedAtTick
                    ? currentTick - record.DisconnectedAtTick
                    : 0ul;

                if (elapsedTicks > (ulong)_disconnectGraceTicks)
                {
                    record.State = SessionState.Closed;
                    if (record.Match.IsValid &&
                        _matches.TryGetValue(record.Match, out var matchRec) &&
                        matchRec.Slots.TryGetValue(record.Player, out var slotRec))
                    {
                        slotRec.State = PlayerConnectionState.Abandoned;
                    }

                    return RebindResult.GraceExpired;
                }
            }

            if (record.Match.IsValid &&
                _matches.TryGetValue(record.Match, out var matchRecord))
            {
                if (matchRecord.Phase == MatchPhase.Finished || matchRecord.Phase == MatchPhase.Closed)
                {
                    return RebindResult.MatchFinished;
                }
            }

            record.State = SessionState.Connected;
            record.Connection = newHandle;
            record.DisconnectedAtTick = 0;

            if (record.Match.IsValid &&
                _matches.TryGetValue(record.Match, out var activeMatch) &&
                activeMatch.Slots.TryGetValue(record.Player, out var slot))
            {
                if (activeMatch.Phase == MatchPhase.Running)
                {
                    slot.State = PlayerConnectionState.Connected;
                    slot.DisconnectedAtTick = 0;
                }
            }

            session = new ClientSession(
                record.Id,
                record.State,
                record.Match,
                record.Player,
                record.Connection,
                record.Secret,
                record.DisconnectedAtTick);

            return RebindResult.Accepted;
        }

        /// <summary>
        /// Terminates a session. When bound to a running match the slot is
        /// abandoned; its PlayerId is retired and never reused (OD-3).
        /// </summary>
        public bool CloseSession(SessionId session)
        {
            if (!_sessions.TryGetValue(session, out var record) ||
                record.State == SessionState.Closed)
            {
                return false;
            }

            if (record.Match.IsValid &&
                _matches.TryGetValue(record.Match, out var matchRecord) &&
                matchRecord.Slots.TryGetValue(record.Player, out var slot) &&
                slot.State != PlayerConnectionState.Abandoned)
            {
                slot.State = PlayerConnectionState.Abandoned;
            }

            record.State = SessionState.Closed;
            return true;
        }

        /// <summary>
        /// Session gate: decides whether a command may reach the
        /// authoritative server. <see cref="CommandHeader"/> is unchanged
        /// (Phase 2.2 contract); attribution comes from the ingress session,
        /// not from the header. All gameplay-level validation remains inside
        /// <see cref="MatchServer"/>.
        /// </summary>
        public SessionRejection ValidateCommand(SessionId session, CommandHeader header)
        {
            if (!_sessions.TryGetValue(session, out var record))
            {
                return SessionRejection.UnknownSession;
            }

            if (record.State == SessionState.Closed)
            {
                return SessionRejection.SessionClosed;
            }

            if (!record.Match.IsValid)
            {
                return SessionRejection.NoBoundMatch;
            }

            if (record.State != SessionState.Connected)
            {
                return SessionRejection.SessionNotConnected;
            }

            if (record.Player != header.Player)
            {
                return SessionRejection.PlayerMismatch;
            }

            if (!_matches.TryGetValue(record.Match, out var matchRecord) ||
                matchRecord.Phase != MatchPhase.Running ||
                !matchRecord.Slots.TryGetValue(record.Player, out var slot) ||
                slot.State != PlayerConnectionState.Connected)
            {
                return SessionRejection.MatchNotRunning;
            }

            return SessionRejection.None;
        }

        /// <summary>
        /// Expires disconnected sessions whose grace window has fully elapsed
        /// at <paramref name="tick"/>: slot → Abandoned, session → Closed.
        /// The hosting layer calls this once per completed server tick; grace
        /// accounting is tick-based (OD-2) and never pauses the simulation.
        /// </summary>
        public void OnTickCompleted(ulong tick)
        {
            foreach (var pair in _sessions)
            {
                var record = pair.Value;
                if (record.State != SessionState.Disconnected ||
                    tick <= record.DisconnectedAtTick + (ulong)_disconnectGraceTicks)
                {
                    continue;
                }

                record.State = SessionState.Closed;

                if (record.Match.IsValid &&
                    _matches.TryGetValue(record.Match, out var matchRecord) &&
                    matchRecord.Slots.TryGetValue(record.Player, out var slot))
                {
                    slot.State = PlayerConnectionState.Abandoned;
                }
            }
        }

        /// <summary>Read-only view of one session, for tests and diagnostics.</summary>
        public bool TryGetSession(SessionId session, out SessionRecord record)
        {
            if (_sessions.TryGetValue(session, out var internalRecord))
            {
                record = new SessionRecord(
                    internalRecord.Id,
                    internalRecord.State,
                    internalRecord.Match,
                    internalRecord.Player,
                    internalRecord.Connection,
                    internalRecord.DisconnectedAtTick,
                    internalRecord.Secret);
                return true;
            }

            record = default;
            return false;
        }

        /// <summary>Read-only view of one client session including secret, for tests and diagnostics.</summary>
        public bool TryGetClientSession(SessionId session, out ClientSession clientSession)
        {
            if (_sessions.TryGetValue(session, out var record))
            {
                clientSession = new ClientSession(
                    record.Id,
                    record.State,
                    record.Match,
                    record.Player,
                    record.Connection,
                    record.Secret,
                    record.DisconnectedAtTick);
                return true;
            }

            clientSession = null;
            return false;
        }

        /// <summary>Read-only view of one player slot, for tests and diagnostics.</summary>
        public bool TryGetPlayerState(MatchId match, PlayerId player, out PlayerConnectionState state)
        {
            if (_matches.TryGetValue(match, out var matchRecord) &&
                matchRecord.Slots.TryGetValue(player, out var slot))
            {
                state = slot.State;
                return true;
            }

            state = default;
            return false;
        }

        /// <summary>Current lifecycle phase of a session-managed match.</summary>
        public bool TryGetMatchPhase(MatchId match, out MatchPhase phase)
        {
            if (_matches.TryGetValue(match, out var matchRecord))
            {
                phase = matchRecord.Phase;
                return true;
            }

            phase = default;
            return false;
        }

        /// <summary>Number of PlayerIds ever assigned to the match (joins, including retired slots).</summary>
        public bool TryGetAssignedCount(MatchId match, out int count)
        {
            if (_matches.TryGetValue(match, out var matchRecord))
            {
                count = matchRecord.AssignedPlayers.Count;
                return true;
            }

            count = 0;
            return false;
        }

        private SessionId CreateUniqueSessionId()
        {
            SessionId candidate;
            do
            {
                candidate = new SessionId(Guid.NewGuid());
            }
            while (_sessions.ContainsKey(candidate));

            return candidate;
        }

        private MatchId CreateUniqueMatchId()
        {
            MatchId candidate;
            do
            {
                candidate = new MatchId(Guid.NewGuid());
            }
            while (_matches.ContainsKey(candidate));

            return candidate;
        }
    }
}
